# Generated by Django 5.1.5 on 2025-01-30 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'grado',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'seccion',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('nombre_padre', models.CharField(max_length=100)),
                ('nombre_madre', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.grado')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.seccion')),
            ],
            options={
                'db_table': 'alumnos',
            },
        ),
    ]
